// <auto-generated />
namespace OpenQbit.Inventory.DAL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTransferDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTransferDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201707100711343_updateTransferDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
